'use client';
import {useEffect,useMemo,useState} from 'react';
import {Upload,BrainCircuit,ClipboardCopy,FileDown,ShieldCheck,Plus,Trash2,Save,FolderOpen,CheckCircle2,AlertTriangle,FileText,Database,WandSparkles} from 'lucide-react';
import type {ExtractedPlan,CurriculumUnit,GeneratedTeachingPlan,Lesson} from '@/lib/types';
import {validatePlan} from '@/lib/validation';

const demoUnit:CurriculumUnit={name:'Instalação e Manutenção Elétrica Predial',workload:100,objective:'Propiciar o desenvolvimento de capacidades técnicas e socioemocionais requeridas para atuar nos processos de instalação e manutenção de sistemas elétricos prediais.',functionText:'Executar processos de instalação, manutenção e elaboração de projetos em sistemas elétricos prediais seguindo procedimentos e Normas Técnicas, de Qualidade, de Segurança, Saúde e Sustentabilidade.',technicalCapabilities:['Selecionar ferramentas e equipamentos para a instalação de acordo com o sistema elétrico predial.','Aplicar as etapas do comissionamento para assegurar necessidades e requisitos operacionais.','Identificar procedimentos técnicos de acordo com o tipo de instalação elétrica predial.','Selecionar materiais e recursos necessários para instalação dos sistemas de acordo com o projeto elétrico.'],socioemotionalCapabilities:['Comprometer-se com comportamentos fundamentados em princípios éticos e códigos de conduta estabelecidos.','Compreender que o trabalho colaborativo pressupõe engajamento e cooperação.','Comprometer-se com princípios, diretrizes, normas e procedimentos, com organização, disciplina, responsabilidade e gestão do tempo.'],knowledge:['Segurança em instalações elétricas','Ferramentas e instrumentos','Diagramas elétricos','Condutores e conexões','Infraestrutura de instalações','Dispositivos de manobra','Tomadas e iluminação','Proteções elétricas','Aterramento','Comissionamento','Manutenção preventiva e corretiva','Documentação técnica e As-Built'],environments:['Sala de aula','Laboratório de Instalações Elétricas'],resources:['Projetor','Painéis didáticos','Ferramentas isoladas','Instrumentos de medição']};

const splitText=(s:string)=>s.split('\n').map(x=>x.replace(/^•\s*/,'').trim()).filter(Boolean);
const joinText=(a:string[]|undefined)=>(a||[]).join('\n');
const slugify=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

function localDraft(unit:CurriculumUnit,totalHours:number,lessonHours:number,strategy:string):GeneratedTeachingPlan{
  const count=Math.max(1,Math.ceil(totalHours/lessonHours));
  const last=totalHours-lessonHours*(count-1);
  const caps=unit.technicalCapabilities.length?unit.technicalCapabilities:['Desenvolver a capacidade técnica prevista para a Unidade Curricular.'];
  const socios=unit.socioemotionalCapabilities.length?unit.socioemotionalCapabilities:['Atuar com organização, responsabilidade e cooperação.'];
  const knowledge=unit.knowledge.length?unit.knowledge:['Conhecimentos previstos no Plano de Curso.'];
  const lessons:Lesson[]=Array.from({length:count},(_,i)=>{
    const c=caps[i%caps.length], s=socios[i%socios.length], k=knowledge[i%knowledge.length];
    return {id:`aula-${i+1}`,number:i+1,durationHours:i===count-1?last:lessonHours,capabilities:[c],socioemotional:[s],knowledge:[k],strategyType:i===0?'Aula expositiva dialogada + diagnóstico':i===count-1?'Projeto integrador + síntese':'Demonstração orientada + prática profissional',strategySteps:`1. Contextualizar o tema ${k}.\n2. Mobilizar conhecimentos prévios.\n3. Apresentar os fundamentos necessários.\n4. Demonstrar o procedimento ou aplicação profissional.\n5. Realizar atividade prática orientada.\n6. Verificar o resultado e corrigir falhas.\n7. Registrar evidências e realizar feedback.`,resources:[...(unit.environments||[]).slice(0,1),...(unit.resources||[]).slice(0,3)],criteria:[`Demonstra a capacidade “${c}” aplicando corretamente os conhecimentos relacionados à atividade.`],instruments:[i===count-1?'Projeto/relatório final com rubrica':'Ficha de observação prática / checklist']};
  });
  return {unit,totalHours,lessonHours,lessonCount:count,learningSituation:{strategy:(strategy==='automática'?'Projeto':strategy) as any,context:`Aplicação integrada dos conhecimentos da Unidade Curricular ${unit.name} em situação profissional contextualizada.`,scenario:`O estudante assume o papel de Técnico em Eletrotécnica responsável por planejar, executar, testar e documentar atividades relacionadas à UC ${unit.name}.`,challenge:`Entregar uma solução técnica segura, funcional e documentada, demonstrando as capacidades previstas no Plano de Curso.`,expectedResults:['Execução técnica conforme requisitos e normas.','Registro das evidências do processo.','Demonstração das capacidades técnicas e socioemocionais previstas.'],evidences:['Produto técnico','Checklist/ficha de observação','Relatório ou registro final']},lessons,warnings:['Rascunho local determinístico. Use “Copiar pedido para Ana” para gerar/revisar com inteligência no ChatGPT.']};
}

export default function Home(){
  const [file,setFile]=useState<File|null>(null); const [extracted,setExtracted]=useState<ExtractedPlan|null>(null); const [selectedIndex,setSelectedIndex]=useState(0);
  const [courseName,setCourseName]=useState('Técnico em Eletrotécnica'); const [unitName,setUnitName]=useState(demoUnit.name); const [totalHours,setTotalHours]=useState(100); const [lessonHours,setLessonHours]=useState(4); const [preferredStrategy,setPreferredStrategy]=useState('automática');
  const [generated,setGenerated]=useState<GeneratedTeachingPlan|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [anaJson,setAnaJson]=useState('');
  const base=extracted?.units?.[selectedIndex]||demoUnit; const unit=useMemo(()=>({...base,name:unitName||base.name}),[base,unitName]); const lessonCount=Math.max(1,Math.ceil(totalHours/Math.max(.5,lessonHours))); const validation=useMemo(()=>generated?validatePlan(generated):null,[generated]);

  useEffect(()=>{try{const s=localStorage.getItem('senai-plano-inteligente:last');if(s){const d=JSON.parse(s);if(d.generated?.lessons){setGenerated(d.generated);setCourseName(d.courseName||courseName);setUnitName(d.generated.unit?.name||unitName);setTotalHours(d.generated.totalHours||100);setLessonHours(d.generated.lessonHours||4)}}}catch{}},[]);

  async function analyzeFile(){if(!file)return setMessage('Selecione o Plano de Curso.');setBusy(true);setMessage('');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/analyze-plan',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setExtracted(d);setSelectedIndex(0);if(d.courseName)setCourseName(d.courseName);if(d.units?.[0]?.name)setUnitName(d.units[0].name);if(d.units?.[0]?.workload)setTotalHours(d.units[0].workload);setMessage(`Leitura concluída: ${d.units?.length||0} UC(s) encontrada(s). A extração é local, sem API.`)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
  function changeUnit(i:number){setSelectedIndex(i);const u=extracted?.units?.[i];if(u?.name)setUnitName(u.name);if(u?.workload)setTotalHours(u.workload)}
  function generateLocal(){setGenerated(localDraft(unit,totalHours,lessonHours,preferredStrategy));setMessage('Rascunho local criado. Para uma versão inteligente, copie o pedido para a Ana e importe o JSON retornado.')}
  function buildPrompt(){return `Ana, gere o Plano de Ensino SENAI em JSON puro, sem markdown, usando EXCLUSIVAMENTE o Plano de Curso que eu anexar nesta conversa e os dados abaixo.\n\nCurso: ${courseName}\nUnidade Curricular: ${unitName}\nCarga horária total: ${totalHours} h\nDuração de cada aula/encontro: ${lessonHours} h\nQuantidade calculada: ${lessonCount} aulas\nEstratégia desafiadora preferida: ${preferredStrategy}\n\nRegras: 1) respeitar capacidades técnicas/básicas, socioemocionais e conhecimentos do Plano de Curso; 2) ordenar por progressão pedagógica e pré-requisitos; 3) em cada aula unir capacidades técnicas e socioemocionais coerentes; 4) escrever estratégia de ensino como passo a passo real da aula; 5) recursos devem corresponder ao tema e à estratégia; 6) critérios devem ser observáveis; 7) instrumentos devem registrar o desempenho; 8) fechar exatamente ${totalHours} h; 9) não inventar capacidades do Plano de Curso.\n\nRetorne exatamente neste formato JSON: {"courseName":"...","generated":{"unit":{"name":"...","workload":${totalHours},"objective":"...","functionText":"...","technicalCapabilities":[],"socioemotionalCapabilities":[],"knowledge":[],"environments":[],"resources":[]},"totalHours":${totalHours},"lessonHours":${lessonHours},"lessonCount":${lessonCount},"learningSituation":{"strategy":"Projeto","context":"...","scenario":"...","challenge":"...","expectedResults":[],"evidences":[]},"lessons":[{"id":"aula-1","number":1,"durationHours":${lessonHours},"capabilities":[],"socioemotional":[],"knowledge":[],"strategyType":"...","strategySteps":"1. ...\\n2. ...","resources":[],"criteria":[],"instruments":[]}],"warnings":[]}}`}
  async function copyPrompt(){await navigator.clipboard.writeText(buildPrompt());setMessage('Pedido copiado. Cole no ChatGPT junto com o Plano de Curso; depois cole aqui o JSON que eu devolver.')}
  function importAna(){try{const start=anaJson.indexOf('{'),end=anaJson.lastIndexOf('}');if(start<0||end<0)throw new Error('JSON não encontrado.');const d=JSON.parse(anaJson.slice(start,end+1));const p=d.generated||d;if(!p?.lessons)throw new Error('Estrutura inválida.');setGenerated(p);if(d.courseName)setCourseName(d.courseName);setUnitName(p.unit?.name||unitName);setTotalHours(p.totalHours||totalHours);setLessonHours(p.lessonHours||lessonHours);setMessage('Plano inteligente importado da Ana com sucesso.')}catch(e:any){setMessage(`Não consegui importar: ${e.message}`)}}
  function patchLesson(id:string,patch:Partial<Lesson>){if(generated)setGenerated({...generated,lessons:generated.lessons.map(l=>l.id===id?{...l,...patch}:l)})}
  function addLesson(){if(!generated)return;const n=generated.lessons.length+1;const l:Lesson={id:`manual-${Date.now()}`,number:n,durationHours:lessonHours,capabilities:[],socioemotional:[],knowledge:[],strategyType:'',strategySteps:'',resources:[],criteria:[],instruments:[]};setGenerated({...generated,lessons:[...generated.lessons,l],lessonCount:n})}
  function deleteLesson(id:string){if(!generated)return;const lessons=generated.lessons.filter(l=>l.id!==id).map((l,i)=>({...l,number:i+1}));setGenerated({...generated,lessons,lessonCount:lessons.length})}
  function saveLocal(){if(!generated)return;localStorage.setItem('senai-plano-inteligente:last',JSON.stringify({courseName,generated}));setMessage('Plano salvo neste navegador.')}
  function importJsonFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const txt=String(reader.result);setAnaJson(txt);try{const d=JSON.parse(txt);const p=d.generated||d;if(!p?.lessons)throw new Error('Estrutura inválida.');setGenerated(p);if(d.courseName)setCourseName(d.courseName);setUnitName(p.unit?.name||unitName);setTotalHours(p.totalHours||totalHours);setLessonHours(p.lessonHours||lessonHours);setMessage('Plano JSON carregado com sucesso.')}catch(e:any){setMessage(`Não consegui importar o arquivo: ${e.message}`)}};reader.readAsText(f)}
  const downloadBlob=(blob:Blob,name:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  function downloadJson(){if(!generated)return;downloadBlob(new Blob([JSON.stringify({courseName,generated},null,2)],{type:'application/json'}),`plano-${slugify(unitName)}.json`)}
  async function downloadDocx(){if(!generated)return;const r=await fetch('/api/export-docx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...generated,courseName})});if(!r.ok)return setMessage('Falha ao gerar Word.');downloadBlob(await r.blob(),`plano-${slugify(unitName)}.docx`)}
  async function downloadPdf(){if(!generated)return;const {jsPDF}=await import('jspdf');const autoTable=(await import('jspdf-autotable')).default;const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});try{const b=await fetch('/senai-header.png').then(r=>r.blob()).then(blob=>new Promise<string>(res=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result));fr.readAsDataURL(blob)}));doc.addImage(b,'PNG',8,5,282,25)}catch{}doc.setFontSize(16);doc.text('PLANO DE ENSINO',148.5,36,{align:'center'});doc.setFontSize(9);doc.text(`Curso: ${courseName}`,10,43);doc.text(`Unidade Curricular: ${generated.unit.name}`,10,48);doc.text(`Carga Horária: ${generated.totalHours}h | Nº de aulas: ${generated.lessonCount}`,10,53);doc.setFontSize(8);const sit=`Estratégia: ${generated.learningSituation.strategy}\nContextualização: ${generated.learningSituation.context}\nCenário: ${generated.learningSituation.scenario}\nDesafio: ${generated.learningSituation.challenge}`;const split=doc.splitTextToSize(sit,277);doc.text(split,10,59);autoTable(doc,{startY:61+split.length*3.5,head:[['Nº / Carga','Capacidades','Conhecimentos','Estratégias de ensino','Recursos','Critérios','Instrumentos']],body:generated.lessons.map(l=>[`${l.number}ª aula\n${l.durationHours}h`,[...l.capabilities,...l.socioemotional].map(x=>`• ${x}`).join('\n'),l.knowledge.map(x=>`• ${x}`).join('\n'),`${l.strategyType}\n${l.strategySteps}`,l.resources.map(x=>`• ${x}`).join('\n'),l.criteria.map(x=>`• ${x}`).join('\n'),l.instruments.map(x=>`• ${x}`).join('\n')]),styles:{fontSize:5.6,cellPadding:1.2,valign:'top'},headStyles:{fillColor:[25,70,145]},margin:{left:8,right:8}});doc.save(`plano-${slugify(unitName)}.pdf`)}

  return <div className="app-shell"><header className="institutional-header"><img src="/senai-header.png" alt="SENAI"/></header><div className="topbar no-print"><div><h1>Plano Inteligente</h1><p>Uso pessoal • sem API • ChatGPT como motor inteligente</p></div><div className="status-pill"><BrainCircuit size={15}/> Modo Ana ativo</div></div><main className="container">
    <section className="hero"><span className="eyebrow">SENAI • ÁREA DE ENERGIA</span><h2>Plano de Ensino por competências, rápido e sem custo extra de API</h2><p>A ferramenta lê o arquivo localmente, calcula as aulas, monta rascunhos, recebe o JSON gerado por mim no ChatGPT, audita a cobertura e exporta Word/PDF.</p><div className="steps no-print"><div>1. Plano</div><div>2. UC</div><div>3. Carga</div><div>4. Ana</div><div>5. Auditoria</div><div>6. Word/PDF</div></div></section>

    <section className="grid grid-2 no-print"><div className="card"><div className="card-title"><Upload size={20}/><h3>1. Ler Plano de Curso</h3></div><div className="dropzone"><FileText size={32}/><strong>PDF, DOCX, TXT ou Markdown</strong><span>A leitura e extração básica acontecem no seu próprio projeto. Nenhuma chave da OpenAI é necessária.</span><input type="file" accept=".pdf,.docx,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><div className="actions"><button className="button primary" disabled={!file||busy} onClick={analyzeFile}><Database size={16}/> {busy?'Lendo...':'Ler arquivo'}</button></div>{extracted&&<div className="alert success"><CheckCircle2 size={16}/> {extracted.units.length} UC(s) encontrada(s)</div>}</div>
    <div className="card"><div className="card-title"><Database size={20}/><h3>2. Unidade Curricular & Carga</h3></div><div className="field"><label>Curso</label><input className="input" value={courseName} onChange={e=>setCourseName(e.target.value)}/></div>{extracted?.units?.length?<div className="field"><label>UC extraída</label><select className="select" value={selectedIndex} onChange={e=>changeUnit(Number(e.target.value))}>{extracted.units.map((u,i)=><option key={i} value={i}>{u.name}</option>)}</select></div>:null}<div className="field"><label>Nome da Unidade Curricular</label><input className="input" value={unitName} onChange={e=>setUnitName(e.target.value)}/></div><div className="grid grid-3"><div className="field"><label>Carga da UC</label><input className="input" type="number" value={totalHours} onChange={e=>setTotalHours(Number(e.target.value)||1)}/></div><div className="field"><label>Horas por aula</label><input className="input" type="number" step=".5" value={lessonHours} onChange={e=>setLessonHours(Number(e.target.value)||.5)}/></div><div className="metric"><strong>{lessonCount}</strong><span>aulas necessárias</span></div></div><div className="field"><label>Estratégia desafiadora</label><select className="select" value={preferredStrategy} onChange={e=>setPreferredStrategy(e.target.value)}><option value="automática">Ana escolhe</option><option>Projeto</option><option>Situação-Problema</option><option>Estudo de Caso</option><option>Pesquisa Aplicada</option></select></div><button className="button ghost full" onClick={generateLocal}><WandSparkles size={17}/> Criar rascunho local agora</button></div></section>

    <section className="card no-print"><div className="card-title"><BrainCircuit size={20}/><h3>3. Usar a Ana com sua assinatura do ChatGPT</h3></div><p style={{color:'#667085',fontSize:13}}>Clique em copiar, cole o pedido nesta conversa junto do Plano de Curso e eu devolvo o JSON inteligente. Depois cole o JSON abaixo e clique em importar.</p><div className="actions"><button className="button orange" onClick={copyPrompt}><ClipboardCopy size={16}/> Copiar pedido para Ana</button></div><div className="field"><label>Resposta JSON da Ana</label><textarea rows={8} value={anaJson} onChange={e=>setAnaJson(e.target.value)} placeholder="Cole aqui o JSON que a Ana devolver..."/></div><div className="actions"><button className="button primary" onClick={importAna}><BrainCircuit size={16}/> Importar Plano Inteligente</button><label className="button ghost file-button"><FolderOpen size={16}/> Importar JSON<input type="file" accept=".json" onChange={importJsonFile}/></label></div></section>

    {message&&<div className={`alert ${message.includes('sucesso')||message.includes('concluída')||message.includes('salvo')||message.includes('criado')?'success':''}`}>{message}</div>}

    {generated&&<><section className="toolbar no-print"><div className="actions"><button className="button ghost" onClick={saveLocal}><Save size={16}/> Salvar local</button><button className="button ghost" onClick={downloadJson}><FileDown size={16}/> JSON</button><button className="button primary" onClick={downloadDocx}><FileDown size={16}/> Word</button><button className="button orange" onClick={downloadPdf}><FileDown size={16}/> PDF</button></div><button className="button ghost" onClick={addLesson}><Plus size={16}/> Adicionar aula</button></section>
    <section className="card"><div className="section-head"><div><span className="eyebrow">SITUAÇÃO DE APRENDIZAGEM</span><h3>{generated.learningSituation.strategy}</h3></div></div><div className="summary-grid"><div><b>Contextualização</b><p>{generated.learningSituation.context}</p></div><div><b>Cenário Profissional</b><p>{generated.learningSituation.scenario}</p></div><div><b>Desafio</b><p>{generated.learningSituation.challenge}</p></div><div><b>Resultados esperados</b><ul>{generated.learningSituation.expectedResults.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div></section>
    {validation&&<section className="audit no-print"><div className="audit-head"><ShieldCheck/><div><strong>Auditoria pedagógica</strong><span>Verificação automática do plano</span></div></div><div className="validation"><div className={`audit-box ${validation.capabilityCoverage===100?'ok':'warn'}`}><strong>{validation.capabilityCoverage}%</strong><span>capacidades</span></div><div className={`audit-box ${validation.knowledgeCoverage===100?'ok':'warn'}`}><strong>{validation.knowledgeCoverage}%</strong><span>conhecimentos</span></div><div className={`audit-box ${validation.hoursPlanned===generated.totalHours?'ok':'warn'}`}><strong>{validation.hoursPlanned}h</strong><span>carga distribuída</span></div><div className={`audit-box ${validation.traceability===100?'ok':'warn'}`}><strong>{validation.traceability}%</strong><span>rastreabilidade</span></div></div>{validation.issues.length>0&&<div className="issue-list">{validation.issues.map((x,i)=><div key={i}><AlertTriangle size={14}/>{x}</div>)}</div>}</section>}
    <section className="card plan-card"><div className="section-head"><div><span className="eyebrow">PLANO DE AULA</span><h3>{generated.unit.name}</h3><p>{generated.totalHours}h • {generated.lessonCount} aulas</p></div></div><div className="table-wrap"><table><thead><tr><th>Nº / Carga</th><th>Capacidades</th><th>Conhecimentos</th><th>Estratégias de ensino</th><th>Recursos</th><th>Critérios</th><th>Instrumentos</th></tr></thead><tbody>{generated.lessons.map(l=><tr key={l.id}><td className="lesson-cell"><b>{l.number}ª aula</b><input className="input" type="number" step=".5" value={l.durationHours} onChange={e=>patchLesson(l.id,{durationHours:Number(e.target.value)})}/><button className="icon-button no-print" onClick={()=>deleteLesson(l.id)}><Trash2 size={14}/></button></td><td><span className="cell-label">Técnicas</span><textarea value={joinText(l.capabilities)} onChange={e=>patchLesson(l.id,{capabilities:splitText(e.target.value)})}/><span className="cell-label socio">Socioemocionais</span><textarea className="small-area" value={joinText(l.socioemotional)} onChange={e=>patchLesson(l.id,{socioemotional:splitText(e.target.value)})}/></td><td><textarea value={joinText(l.knowledge)} onChange={e=>patchLesson(l.id,{knowledge:splitText(e.target.value)})}/></td><td><input className="input strategy-input" value={l.strategyType} onChange={e=>patchLesson(l.id,{strategyType:e.target.value})}/><textarea className="steps-area" value={l.strategySteps} onChange={e=>patchLesson(l.id,{strategySteps:e.target.value})}/></td><td><textarea value={joinText(l.resources)} onChange={e=>patchLesson(l.id,{resources:splitText(e.target.value)})}/></td><td><textarea value={joinText(l.criteria)} onChange={e=>patchLesson(l.id,{criteria:splitText(e.target.value)})}/></td><td><textarea value={joinText(l.instruments)} onChange={e=>patchLesson(l.id,{instruments:splitText(e.target.value)})}/></td></tr>)}</tbody></table></div></section></>}
  </main><footer className="footer">SENAI • Plano Inteligente V3 — uso pessoal • sem chave de API</footer></div>
}
